web:
  enabled: true
  parameters:
    host: "0.0.0.0"
    port: 8080
    monitor_subscriber_addr: "/tmp/monitoring"
    monitor_topic: "monitoring"
    evolution_threshold: 5000

local:
  enabled: true
  parameters:
    monitor_publisher_addr: "/tmp/monitoring"
    monitor_topic: "monitoring"
    frame_publisher_addr: "/tmp/frame"
    frame_topic: "frame"
    analysis_subscriber_addr: "/tmp/analysis"
    analysis_topic: "analysis"
    head_direction_std_weight: 60
    ear_threshold: 0.30

processing:
  enabled: true
  parameters:
    frame_subscriber_addr: "/tmp/frame"
    frame_topic: "frame"
    analysis_publisher_addr: "/tmp/analysis"
    analysis_topic: "analysis"
